---
- hosts: f5_bigiq_cm
  connection: local
  serial: 1
  gather_facts: false
  vars:
    provider:
      server: "{{ hostvars[groups['f5_bigiq_cm'][0]]['ansible_host'] }}"
      server_port: 443
      user: david
      password: david
      auth_provider: RadiusServer # for local auth, use "tmos"
      validate_certs: false

  tasks:
    - debug: var=provider

    - name: AS3 deploy
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_service: AS3
        atc_method: POST
        atc_declaration_file: "{{ as3app }}"
        atc_delay: 15
        atc_retries: 30
      register: atc_AS3_status

    - debug: var=atc_AS3_status