---
# Creates auto scaling resources on BIG-IQ
- name: Make BIG IQ Auto Scaling Resources
  hosts: bigiq-01
  vars_files:     
    - ./config.yml
  become: root
  tasks:             
    - include_tasks: ./helpers/post.yml
      with_items:
        - name: Create service scaling group          
          url: "{{BIGIQ_URI}}/cm/cloud/service-scaling-groups"          
          body: >
            {
                "name": "{{SSG_NAME}}",
                "description": "VMware scaling group",
                "environmentReference": {
                    "link": "https://localhost/mgmt/cm/cloud/environments/4aebc2cf-79a4-335a-98cb-782de1117e55"
                },
                "loadBalancerDeviceReferences": [
                {
                    "link": "https://localhost/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices/ba7382a4-7564-4647-b65d-17d6f2a73a16"
                },
                {
                    "link": "https://localhost/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices/57dfa09f-019d-478e-bac3-50a20e55cd20"
                }],
                "minSize": 1,
                "maxSize": 3,
                "maxSupportedApplications": 3,
                "desiredSize": 1,
                "providerType": "Vmware",
                "postDeviceCreationUserScriptReference": null,
                "preDeviceDeletionUserScriptReference": null,
                "scalingPolicies": [
                {
                    "name": "scale-out",
                    "cooldown": 15,
                    "direction": "ADD",
                    "type": "ChangeCount",
                    "value": 1
                },
                {
                    "name": "scale-in",
                    "cooldown": 15,
                    "direction": "REMOVE",
                    "type": "ChangeCount",
                    "value": 1
                }]
            }

          var_name: ssg_result
          
    - include_tasks: ./helpers/post.yml
      with_items:
        - name: Creating scale in alert      
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"      
          body: >
            {
                "name": "{{SSG_NAME}}-device-scale-in",
                "alertTypeId": "device-scale-in-recommendation",
                "isDefault": false,
                "producerType": "device",
                "alertType": "active",
                "alertContext": "scale-in-recommendation",
                "includeInternalAlerts": false,
                "aggregationMethod": "and",
                "external": "true",
                "nestedRules": [
                {
                    "alertTypeId": "device-cpu",
                    "alertRuleType": "nested-metric",
                    "warningThreshold": 3,
                    "errorThreshold": 5,
                    "unit": "percent",
                    "operator": "less-than",
                    "enabled": true
                },
                {
                    "alertTypeId": "device-throughput-in",
                    "alertRuleType": "nested-metric",
                    "warningThreshold": 5,
                    "errorThreshold": 10,
                    "unit": "Mbps",
                    "operator": "greater-than",
                    "enabled": true
                }],
                "ssgReferences": [
                {
                    "name": "{{SSG_NAME}}",
                    "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }],
                "alertRuleType": "aggregated",
                "isPublic": false
            }            

        - name: Creating scale in alert OR     
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"      
          body: >
            {
              "aggregationMethod": "or",
              "producerType": "ssg",
              "name": "{{SSG_NAME}}-device-scale-in",
              "alertTypeId": "ssg-scale-in-recommendation",
              "includeInternalAlerts": true,
              "alertRuleReferences": [
                {
                  "name": "{{SSG_NAME}}-device-scale-in",
                  "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-device-scale-in"
                }
              ],
              "external": true,
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertContext": "scale-in-recommendation",
              "alertRuleType": "aggregated",
              "alertType": "active",
              "isDefault": false,
              "isPublic": false
            }

            
        - name: Create scale in workflow rule              
          identifier_name: workflowRuleName       
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/workflow-rules"          
          body: >
            {
              "workflowRuleName": "{{SSG_NAME}}-scale-in",
              "workflowParameters": {
                "parameters": {
                  "ssgName": "{{SSG_NAME}}",
                  "scalingPolicyName": "scale-in"
                }
              },
              "targetWorkflowUri": "https://localhost/mgmt/cm/cloud/tasks/handle-scaling-alert",
              "alertRuleReference": {
                "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-ssg-scale-in"
              },
              "sendEmail": false,
              "sendEmailContacts": null,
              "sendSNMP": false
            }

        - name: Creating scale out alert
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"
          body: >
            {
              "aggregationMethod": "or",
              "producerType": "device",
              "name": "{{SSG_NAME}}-device-scale-out",
              "alertTypeId": "device-scale-out-recommendation",
              "includeInternalAlerts": false,
              "nestedRules": [
                {
                  "alertRuleType": "nested-metric",
                  "alertTypeId": "device-cpu",
                  "warningThreshold": 65,
                  "errorThreshold": 75,
                  "unit": "percent",
                  "operator": "greater-than",
                  "enabled": true
                },
                {
                  "alertRuleType": "nested-metric",
                  "alertTypeId": "device-throughput-in",
                  "warningThreshold": 20,
                  "errorThreshold": 25,
                  "unit": "M",
                  "operator": "greater-than",
                  "enabled": true
                }
              ],
              "external": true,
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertContext": "scale-out-recommendation",
              "alertRuleType": "aggregated",
              "alertType": "active",
              "isDefault": false,
              "isPublic": false
            }

        - name: Create scale in alert           
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"          
          body: >
            {
              "aggregationMethod": "or",
              "producerType": "ssg",
              "name": "{{SSG_NAME}}-ssg-scale-out",
              "alertTypeId": "ssg-scale-out-recommendation",
              "includeInternalAlerts": true,
              "alertRuleReferences": [
                {
                  "name": "{{SSG_NAME}}-device-scale-out",
                  "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-device-scale-out"
                }
              ],
              "external": true,
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertContext": "scale-out-recommendation",
              "alertRuleType": "aggregated",
              "alertType": "active",
              "isDefault": false,
              "isPublic": false
            }

        - name: Create scale in workflow rule              
          identifier_name: workflowRuleName       
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/workflow-rules"          
          body: >
            {
              "workflowRuleName": "{{SSG_NAME}}-scale-out",
              "workflowParameters": {
                "parameters": {
                  "ssgName": "{{SSG_NAME}}",
                  "scalingPolicyName": "scale-out"
                }
              },
              "targetWorkflowUri": "https://localhost/mgmt/cm/cloud/tasks/handle-scaling-alert",
              "alertRuleReference": {
                "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-ssg-scale-out"
              },
              "sendEmail": false,
              "sendEmailContacts": null,
              "sendSNMP": false
            }

        - name: Create scale out alert          
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"            
          body: >
            {
              "name": "{{SSG_NAME}}-active-device-health",
              "alertTypeId": "device-health",
              "isDefault": false,
              "isPublic": false,
              "producerType": "device",
              "alertType": "active",
              "alertContext": "health",
              "includeInternalAlerts": true,
              "aggregationMethod": "or",
              "alertRuleType": "aggregated",
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "external": true,
              "nestedRules": [
                {
                  "alertRuleType": "nested-metric",
                  "alertTypeId": "device-cpu",
                  "unit": "percent",
                  "operator": "greater-than",
                  "enabled": true,
                  "warningThreshold": 65,
                  "errorThreshold": 75
                }
              ]
            }        

        - name: Create scale out workflow rule       
          identifier_name: workflowRuleName    
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/workflow-rules"
          body: >
            {
              "workflowRuleName": "{{SSG_NAME}}-health",
              "workflowParameters": {
                "parameters": {
                  "ssgName": "{{SSG_NAME}}"
                }
              },
              "alertRuleReference": {
                "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-active-device-health"
              },
              "sendEmail": false,
              "sendEmailContacts": null,
              "sendSNMP": false
            }

        - name: Create scale out alert          
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"            
          body: >
            {
              "name": "{{SSG_NAME}}-active-ssg-health",
              "alertTypeId": "ssg-health",
              "isDefault": false,
              "producerType": "ssg",
              "alertType": "active",
              "alertContext": "health",
              "includeInternalAlerts": true,
              "aggregationMethod": "or",
              "external": true,
              "alertRuleType": "aggregated",
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertRuleReferences": [
                {
                  "name": "{{SSG_NAME}}-active-device-health",
                  "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-active-device-health"
                }
              ]
            }           
...
