---
# This file establishes the necessary resources on AWS to create a VPN connection to the previously created VPC
- name: Create VPN resources
  hosts: localhost
  vars_files:
    - ./config.yml
    - ./cache/{{PREFIX}}/1-vpc.yml
  tasks:
    - name: Set AWS Region
      command: aws configure set default.region {{DEFAULT_REGION}}

    - name: Build VPN CloudFormation
      cloudformation:
        stack_name: "{{PREFIX}}-vpn-cf-stack"
        template: ./cft/Setup-VPN.template
        template_parameters:
          VPCID: "{{AWS_VPC}}"
          RT1ID: "{{RT1Id}}"
          RT2ID: "{{RT2Id}}"
          REGION: "{{DEFAULT_REGION}}"
          VPNNAME: "{{PREFIX}}-vpn"
          CUSTOMERGATEWAYIP: "{{CUSTOMER_GATEWAY_IP}}"
      register: vpn_stack

...

