---
# This file establishes the necessary resources on AWS to create a Demo Webserver using Ubuntu
- name: Create Ubuntu resources
  hosts: localhost
  vars_files:
    - ./config.yml
    - ./cache/{{PREFIX}}/1-vpc.yml
  tasks:
    - name: Set AWS Region
      command: aws configure set default.region {{DEFAULT_REGION}}

    - name: Build Ubuntu CloudFormation
      cloudformation:
        stack_name: "{{PREFIX}}-ubuntu-cf-stack"
        template: ./cft/Setup-Ubuntu.template
        template_parameters:
          VPCID: "{{AWS_VPC}}"
          EC2NAME: "{{PREFIX}}-server"
          KEYNAME: "{{AWS_SSH_KEY}}"
          REGION: "{{DEFAULT_REGION}}"
          INTERNALSUB: "{{AWS_SUBNET_1B}}"
          UBUNTUIPADDRESS: "{{NODE_ADDRESS}}"
      register: ubuntu_stack

...

