---
# Creates auto scaling resources on BIG-IQ
- name: Make BIG IQ Auto Scaling Resources
  hosts: bigiq-01
  vars_files:     
    - ./config.yml
    - ./cache/{{PREFIX}}/1-vpc.yml
  become: root
  tasks:             
    - name: Create resources
      include_tasks: ./helpers/post.yml
      with_items:
        - name: Create device template
          url: "{{BIGIQ_URI}}/cm/device/templates"
          body: > 
            {
                "name": "{{DEVICE_TEMPLATE_NAME}}",
                "type": "AWS",
                "timeZone": "UTC",
                "ntpServerList": [ "{{NTP_SERVER}}" ],
                "userAccountList": [
                    {
                        "username": "{{BIGIP_USER}}",
                        "password": "{{BIGIP_PWD}}",
                        "role": "admin"
                    }
                ]
            }

          var_name: device_template_result

    - include_tasks: ./helpers/post.yml
      with_items:
        - name: Creating cloud provider
          url: "{{BIGIQ_URI}}/cm/cloud/providers"
          body: >
            {
                "providerType": "AWS",
                "name": "{{CLOUD_PROVIDER_NAME}}",
                "description": "AWS cloud provider",
                "awsProperties": {
                    "awsCloud": "{{AWS_BIGIQ_CLOUD}}",
                    "accessKeyId": "{{AWS_ACCESS_KEY_ID}}",
                    "secretAccessKey": "{{AWS_SECRET_ACCESS_KEY}}"
                }
            }

          var_name: cloud_provider_result

    - include_tasks: ./helpers/post.yml
      with_items:
        - name: Creating cloud environment SSG
          url: "{{BIGIQ_URI}}/cm/cloud/environments"
          body: >
            {
                "name": "{{CLOUD_ENVIRONMENT_NAME}}_SSG",
                "description": "AWS cloud environment for SSG",
                "providerReference": {
                    "link": "https://localhost/mgmt/cm/cloud/providers/{{cloud_provider_result.id}}"
                },
                "deviceTemplateReference": {
                    "link": "https://localhost/mgmt/cm/device/templates/{{device_template_result.id}}"
                },
                "awsProperties": {
                    "region": "{{DEFAULT_REGION}}",
                    "vpc": "{{AWS_VPC}}",
                    "availabilityZones": [ "{{AWS_AZ_1A}}", "{{AWS_AZ_1B}}" ],
                    "subnets": [ "{{AWS_SUBNET_1A}}", "{{AWS_SUBNET_1B}}" ],
                    "restrictedSourceAddress": "0.0.0.0/0",
                    "sshKeyName": "{{AWS_SSH_KEY}}",
                    "moduleSelection": "{{MODULE}}",
                    "licenseType": "BYOL",
                    "imageId": "{{BYOL_BIGIP_AMI}}",
                    "instanceType": "m4.xlarge",
                    "byolLicenseInformation": {
                        "bigiqAddress": "{{BYOL_BIGIQ_HOST}}",
                        "bigiqUser": "{{BYOL_BIGIQ_USER}}",
                        "bigiqPassword": "{{BYOL_BIGIQ_PWD}}",  
                        "licensePoolName": "{{BYOL_POOL_NAME}}"
                    }
                }
            }

          var_name: cloud_environment_result

    # - fail: msg="ALTO"

    - include_tasks: ./helpers/post.yml
      with_items:
        - name: Create service scaling group          
          url: "{{BIGIQ_URI}}/cm/cloud/service-scaling-groups"          
          body: >
            {
                "name": "{{SSG_NAME}}",
                "description": "AWS scaling group",
                "environmentReference": {
                    "link": "https://localhost/mgmt/cm/cloud/environments/{{cloud_environment_result.id}}"
                },
                "minSize": 1,
                "maxSize": 3,
                "maxSupportedApplications": 3,
                "desiredSize": 1,
                "providerType": "AWS",
                "postDeviceCreationUserScriptReference": null,
                "preDeviceDeletionUserScriptReference": null,
                "scalingPolicies": [
                {
                    "name": "scale-out",
                    "cooldown": 15,
                    "direction": "ADD",
                    "type": "ChangeCount",
                    "value": 1
                },
                {
                    "name": "scale-in",
                    "cooldown": 15,
                    "direction": "REMOVE",
                    "type": "ChangeCount",
                    "value": 1
                }]
            }

          var_name: ssg_result
          
    - include_tasks: ./helpers/post.yml
      with_items:
        - name: Creating scale in alert      
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"      
          body: >
            {
                "name": "{{SSG_NAME}}-device-scale-in",
                "alertTypeId": "device-scale-in-recommendation",
                "isDefault": false,
                "producerType": "device",
                "alertType": "active",
                "alertContext": "scale-in-recommendation",
                "includeInternalAlerts": false,
                "aggregationMethod": "and",
                "external": "true",
                "nestedRules": [
                {
                    "alertTypeId": "device-cpu",
                    "alertRuleType": "nested-metric",
                    "warningThreshold": 3,
                    "errorThreshold": 5,
                    "unit": "percent",
                    "operator": "less-than",
                    "enabled": true
                },
                {
                    "alertTypeId": "device-throughput-in",
                    "alertRuleType": "nested-metric",
                    "warningThreshold": 5,
                    "errorThreshold": 10,
                    "unit": "Mbps",
                    "operator": "greater-than",
                    "enabled": true
                }],
                "ssgReferences": [
                {
                    "name": "{{SSG_NAME}}",
                    "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }],
                "alertRuleType": "aggregated",
                "isPublic": false
            }            

        - name: Creating scale in alert OR     
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"      
          body: >
            {
              "aggregationMethod": "or",
              "producerType": "ssg",
              "name": "{{SSG_NAME}}-device-scale-in",
              "alertTypeId": "ssg-scale-in-recommendation",
              "includeInternalAlerts": true,
              "alertRuleReferences": [
                {
                  "name": "{{SSG_NAME}}-device-scale-in",
                  "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-device-scale-in"
                }
              ],
              "external": true,
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertContext": "scale-in-recommendation",
              "alertRuleType": "aggregated",
              "alertType": "active",
              "isDefault": false,
              "isPublic": false
            }

            
        - name: Create scale in workflow rule              
          identifier_name: workflowRuleName       
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/workflow-rules"          
          body: >
            {
              "workflowRuleName": "{{SSG_NAME}}-scale-in",
              "workflowParameters": {
                "parameters": {
                  "ssgName": "{{SSG_NAME}}",
                  "scalingPolicyName": "scale-in"
                }
              },
              "targetWorkflowUri": "https://localhost/mgmt/cm/cloud/tasks/handle-scaling-alert",
              "alertRuleReference": {
                "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-ssg-scale-in"
              },
              "sendEmail": false,
              "sendEmailContacts": null,
              "sendSNMP": false
            }

        - name: Creating scale out alert
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"
          body: >
            {
              "aggregationMethod": "or",
              "producerType": "device",
              "name": "{{SSG_NAME}}-device-scale-out",
              "alertTypeId": "device-scale-out-recommendation",
              "includeInternalAlerts": false,
              "nestedRules": [
                {
                  "alertRuleType": "nested-metric",
                  "alertTypeId": "device-cpu",
                  "warningThreshold": 65,
                  "errorThreshold": 75,
                  "unit": "percent",
                  "operator": "greater-than",
                  "enabled": true
                },
                {
                  "alertRuleType": "nested-metric",
                  "alertTypeId": "device-throughput-in",
                  "warningThreshold": 20,
                  "errorThreshold": 25,
                  "unit": "M",
                  "operator": "greater-than",
                  "enabled": true
                }
              ],
              "external": true,
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertContext": "scale-out-recommendation",
              "alertRuleType": "aggregated",
              "alertType": "active",
              "isDefault": false,
              "isPublic": false
            }

        - name: Create scale in alert           
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"          
          body: >
            {
              "aggregationMethod": "or",
              "producerType": "ssg",
              "name": "{{SSG_NAME}}-ssg-scale-out",
              "alertTypeId": "ssg-scale-out-recommendation",
              "includeInternalAlerts": true,
              "alertRuleReferences": [
                {
                  "name": "{{SSG_NAME}}-device-scale-out",
                  "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-device-scale-out"
                }
              ],
              "external": true,
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertContext": "scale-out-recommendation",
              "alertRuleType": "aggregated",
              "alertType": "active",
              "isDefault": false,
              "isPublic": false
            }

        - name: Create scale in workflow rule              
          identifier_name: workflowRuleName       
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/workflow-rules"          
          body: >
            {
              "workflowRuleName": "{{SSG_NAME}}-scale-out",
              "workflowParameters": {
                "parameters": {
                  "ssgName": "{{SSG_NAME}}",
                  "scalingPolicyName": "scale-out"
                }
              },
              "targetWorkflowUri": "https://localhost/mgmt/cm/cloud/tasks/handle-scaling-alert",
              "alertRuleReference": {
                "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-ssg-scale-out"
              },
              "sendEmail": false,
              "sendEmailContacts": null,
              "sendSNMP": false
            }

        - name: Create scale out alert          
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"            
          body: >
            {
              "name": "{{SSG_NAME}}-active-device-health",
              "alertTypeId": "device-health",
              "isDefault": false,
              "isPublic": false,
              "producerType": "device",
              "alertType": "active",
              "alertContext": "health",
              "includeInternalAlerts": true,
              "aggregationMethod": "or",
              "alertRuleType": "aggregated",
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "external": true,
              "nestedRules": [
                {
                  "alertRuleType": "nested-metric",
                  "alertTypeId": "device-cpu",
                  "unit": "percent",
                  "operator": "greater-than",
                  "enabled": true,
                  "warningThreshold": 65,
                  "errorThreshold": 75
                }
              ]
            }        

        - name: Create scale out workflow rule       
          identifier_name: workflowRuleName    
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/workflow-rules"
          body: >
            {
              "workflowRuleName": "{{SSG_NAME}}-health",
              "workflowParameters": {
                "parameters": {
                  "ssgName": "{{SSG_NAME}}"
                }
              },
              "alertRuleReference": {
                "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-active-device-health"
              },
              "sendEmail": false,
              "sendEmailContacts": null,
              "sendSNMP": false
            }

        - name: Create scale out alert          
          url: "{{BIGIQ_URI}}/cm/shared/policymgmt/alert-rules"            
          body: >
            {
              "name": "{{SSG_NAME}}-active-ssg-health",
              "alertTypeId": "ssg-health",
              "isDefault": false,
              "producerType": "ssg",
              "alertType": "active",
              "alertContext": "health",
              "includeInternalAlerts": true,
              "aggregationMethod": "or",
              "external": true,
              "alertRuleType": "aggregated",
              "ssgReferences": [
                {
                  "name": "{{SSG_NAME}}",
                  "link": "https://localhost/mgmt/cm/cloud/service-scaling-groups/{{ssg_result.id}}"
                }
              ],
              "alertRuleReferences": [
                {
                  "name": "{{SSG_NAME}}-active-device-health",
                  "link": "https://localhost/mgmt/cm/shared/policymgmt/alert-rules/{{SSG_NAME}}-active-device-health"
                }
              ]
            }           
...
