---
# Delete all auto scaling resources from BIG-IQ
- name: Tear down SSG resources (Cloud Environment)
  hosts: bigiq-01
  vars_files:
    - ./config.yml
  vars:
    CURL_CMD: curl -s -k -u {{BIGIQ_USER}}:{{BIGIQ_PWD}}
  become: true
  become_user: root
  tasks:
    # Teardown errors are usually from trying to delete an item that's already gone
    - ignore_errors: yes
      block:
        - name: Get SSG cloud env to delete
          uri:
            url: "{{BIGIQ_URI}}/cm/cloud/environments/"
            method: GET
          register: ssg_result

        - name: Save JQ Command
          set_fact:
            jq_command: "json.items[?name=='{{CLOUD_ENVIRONMENT_NAME}}'].id"

        - set_fact:
            ssg_ids: "{{ssg_result|json_query(jq_command)}}"

        - name: Scrape SSG ID out of response
          set_fact:
            ssg_id: "{{ssg_ids[0]}}"

        - name: Deleting SSG Cloud Environment
          uri:
            url: "{{BIGIQ_URI}}/cm/cloud/environments/{{ssg_id}}"
            method: DELETE
...
