version: '2'
services:

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab-web'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.1.1.5:7002'
        gitlab_rails['gitlab_shell_ssh_port'] = 7022
        gitlab_rails['initial_root_password'] = 'purple123'
    ports:
      - '7002:7002'
      - '7022:22'
    volumes:
      - '$GITLAB_HOME/gitlab/config:/etc/gitlab'
      - '$GITLAB_HOME/gitlab/logs:/var/log/gitlab'
      - '$GITLAB_HOME/gitlab/data:/var/opt/gitlab'

  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner1
    hostname: gitlab-runner1.example.com
    volumes:
      - '$GITLAB_HOME/gitlab-runner1-config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'
