---
# Delete all auto scaling resources from BIG-IQ
- name: Tear down SSG resources
  hosts: bigiq-01
  vars_files:
    - ./config.yml
  vars:
    CURL_CMD: curl -s -k -u {{BIGIQ_USER}}:{{BIGIQ_PWD}}
  become: true
  become_user: root
  tasks:
    # Teardown errors are usually from trying to delete an item that's already gone
    - ignore_errors: yes
      block:
        - name: Get SSG to delete
          uri:
            url: "{{BIGIQ_URI}}/cm/cloud/service-scaling-groups"
            method: GET
          register: ssg_result

        - name: Save JQ Command
          set_fact:
            jq_command: "json.items[?name=='{{SSG_NAME}}'].id"

        - set_fact:
            ssg_ids: "{{ssg_result|json_query(jq_command)}}"

        - name: Scrape SSG ID out of response
          set_fact:
            ssg_id: "{{ssg_ids[0]}}"

        - name: Deleting service scaling group
          uri:
            url: "{{BIGIQ_URI}}/cm/cloud/service-scaling-groups/{{ssg_id}}"
            method: PATCH
            body_format: json
            body: '{ "status": "DELETING" }'

...
